version: "3"

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
  web:
    build: .
    env_file:
      - .env
    volumes:
      - ./src/spotifast:/usr/src/spotifast
    ports:
      - "8000:8000"
    depends_on:
      - postgres
